import React from "react";
import { CodeBlock } from "@/components/ui/code-block";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { FileJson, Hash, Coins, Clock, ShieldCheck, Users, AlertTriangle, GitBranch, Lock } from "lucide-react";

function FieldRow({ name, type, value, desc }: { name: string; type: string; value: string; desc: string }) {
  return (
    <tr className="border-b border-border/50 last:border-0">
      <td className="py-2.5 pr-3 align-top">
        <code className="text-xs font-mono text-primary font-semibold">{name}</code>
        <div className="text-[10px] text-muted-foreground/70 mt-0.5">{type}</div>
      </td>
      <td className="py-2.5 pr-3 align-top">
        <code className="text-xs font-mono text-foreground">{value}</code>
      </td>
      <td className="py-2.5 align-top text-xs text-muted-foreground">{desc}</td>
    </tr>
  );
}

function StatTile({ icon: Icon, label, value, sub }: { icon: any; label: string; value: string; sub: string }) {
  return (
    <Card>
      <CardHeader className="pb-2">
        <CardDescription className="flex items-center gap-2 text-xs uppercase tracking-wide">
          <Icon className="w-3.5 h-3.5" /> {label}
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="text-2xl font-bold text-foreground font-mono">{value}</div>
        <p className="text-xs text-muted-foreground mt-1">{sub}</p>
      </CardContent>
    </Card>
  );
}

export default function Genesis() {
  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* Hero */}
      <div>
        <div className="flex items-center gap-2 mb-3">
          <Badge variant="outline" className="border-primary/40 text-primary">Chain Bootstrap</Badge>
          <Badge variant="outline" className="text-muted-foreground">Phase A · LIVE</Badge>
        </div>
        <h1 className="text-3xl font-bold tracking-tight text-foreground mb-3">
          Genesis Configuration
        </h1>
        <p className="text-lg text-muted-foreground max-w-3xl">
          The genesis file pins the chain's identity, supply, founder validator, and any pre-mine
          allocations into a deterministic JSON document. Every node that joins the network must
          load <strong>byte-identical</strong> genesis state — otherwise it will diverge at block 1.
        </p>
      </div>

      {/* Quick stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <StatTile icon={Hash} label="Chain ID" value="7878" sub="ZVM hex: 0x1ec6" />
        <StatTile icon={Coins} label="Token" value="ZBX" sub="18 decimals · cap 150M" />
        <StatTile icon={Clock} label="Block time" value="5 sec" sub="Constant — no jitter" />
        <StatTile icon={Users} label="Genesis validator" value="1" sub="Founder, deterministic" />
      </div>

      {/* Anatomy */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <FileJson className="w-4 h-4 text-primary" /> Anatomy of <code className="text-sm">genesis.json</code>
          </CardTitle>
          <CardDescription>
            Generated by <code className="text-xs bg-muted px-1 rounded">zebvix-node init</code> and
            written to <code className="text-xs bg-muted px-1 rounded">&lt;--home&gt;/genesis.json</code>{" "}
            (default <code className="text-xs bg-muted px-1 rounded">./.zebvix/genesis.json</code>).
            Source of truth: <code className="text-xs bg-muted px-1 rounded">struct GenesisFile</code> in <code className="text-xs bg-muted px-1 rounded">zebvix-chain/src/main.rs</code>.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border text-left text-xs uppercase tracking-wide text-muted-foreground">
                  <th className="py-2 pr-3 font-medium">Field</th>
                  <th className="py-2 pr-3 font-medium">Default value</th>
                  <th className="py-2 font-medium">Purpose</th>
                </tr>
              </thead>
              <tbody>
                <FieldRow
                  name="chain_id"
                  type="u64"
                  value="7878"
                  desc="EIP-155 chain ID. Hex 0x1ec6. Prevents tx replay across other ZVM networks."
                />
                <FieldRow
                  name="chain_name"
                  type="String"
                  value={'"Zebvix"'}
                  desc="Human-readable network name surfaced by RPC and explorers."
                />
                <FieldRow
                  name="token_symbol"
                  type="String"
                  value={'"ZBX"'}
                  desc="Native gas token ticker."
                />
                <FieldRow
                  name="decimals"
                  type="u32"
                  value="18"
                  desc="Smallest unit = wei = 10⁻¹⁸ ZBX. Matches Ethereum convention."
                />
                <FieldRow
                  name="max_supply_wei"
                  type="String (decimal)"
                  value="150000000000000000000000000"
                  desc="Hard cap = 150,000,000 ZBX. Mining halts once cumulative reward + premine reach this."
                />
                <FieldRow
                  name="block_time_secs"
                  type="u64"
                  value="5"
                  desc="Target inter-block interval. Used by consensus deadline + epoch length math."
                />
                <FieldRow
                  name="validator_address"
                  type="String (hex)"
                  value="0x40907000…0c0315"
                  desc="20-byte address of THIS node's local key (informational). The actual genesis validator set is bound deterministically — see below."
                />
                <FieldRow
                  name="alloc"
                  type="Vec<(String, String)>"
                  value="[(founder_hex, premine_wei)]"
                  desc="Initial balances minted at height 0. Tuple is (20-byte hex address, decimal wei amount). Default = 9,990,000 ZBX (6.66%) Foundation pre-mine to the validator address."
                />
                <FieldRow
                  name="timestamp"
                  type="i64 (unix)"
                  value="<utc now>"
                  desc="Wall-clock epoch second when init was run. Used as block 0 time."
                />
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      {/* Founder validator deterministic */}
      <Card className="border-primary/30">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <ShieldCheck className="w-4 h-4 text-primary" /> Founder validator is deterministic
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-sm text-muted-foreground">
          <p>
            Independent of which key file you pass to{" "}
            <code className="text-xs bg-muted px-1 rounded">--validator-key</code>, every freshly
            initialized Zebvix home registers the <strong>same</strong> founder validator (built
            from <code className="text-xs bg-muted px-1 rounded">FOUNDER_PUBKEY_HEX</code>{" "}
            baked into the binary at compile time, voting power = 1). This is intentional — it
            eliminates the "genesis validator divergence" bug where every operator's local key
            ended up in a different genesis registry, fork-splitting the network on the very first
            block.
          </p>
          <p>
            If your local key is <em>not</em> the founder, you'll see this notice during{" "}
            <code className="text-xs bg-muted px-1 rounded">init</code>:
          </p>
          <CodeBlock
            language="text"
            code={`ℹ️  Genesis validator (founder, deterministic): 0x40907000ac0a1a73e4cd89889b4d7ee8980c0315 (power=1)
ℹ️  Local validator key 0xab12... is NOT the founder — it must be added
    post-genesis via \`validator-add\` tx (admin-signed).`}
          />
          <p className="text-xs text-muted-foreground italic">
            On-chain rule (enforced in <code className="bg-muted px-1 rounded not-italic">state.rs::apply_tx</code>):
            adding a new validator requires the <strong>current governor</strong> to sign the{" "}
            <code className="bg-muted px-1 rounded not-italic">ValidatorAdd</code> tx — same forkless
            governance flow used for parameter changes.
          </p>
          <p>
            New validators are activated only through the two-tier governance flow on the{" "}
            <strong>Validator Setup</strong> page: a{" "}
            <code className="text-xs bg-muted px-1 rounded">StakeOp::CreateValidator</code> tx puts
            up the bond, then a <strong>governor-signed</strong>{" "}
            <code className="text-xs bg-muted px-1 rounded">ValidatorAdd</code> tx promotes the
            address into the active set. Block-apply replication ensures all peers converge.
          </p>
        </CardContent>
      </Card>

      {/* Real example */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <FileJson className="w-4 h-4 text-primary" /> Real <code className="text-sm">genesis.json</code> from VPS
          </CardTitle>
          <CardDescription>
            This is exactly what <code className="text-xs bg-muted px-1 rounded">zebvix-node init</code>{" "}
            wrote on <code className="text-xs bg-muted px-1 rounded">srv1266996</code> when the
            Phase-A network was bootstrapped.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <CodeBlock
            language="json"
            code={`{
  "chain_id": 7878,
  "chain_name": "Zebvix",
  "token_symbol": "ZBX",
  "decimals": 18,
  "max_supply_wei": "150000000000000000000000000",
  "block_time_secs": 5,
  "validator_address": "0x40907000ac0a1a73e4cd89889b4d7ee8980c0315",
  "alloc": [
    [
      "0x40907000ac0a1a73e4cd89889b4d7ee8980c0315",
      "9990000000000000000000000"
    ]
  ],
  "timestamp": 1735776000
}`}
          />
          <div className="rounded-md border border-amber-500/30 bg-amber-500/5 p-3 text-xs text-amber-200/90 mt-3 flex gap-2">
            <AlertTriangle className="w-4 h-4 flex-shrink-0 mt-0.5" />
            <span>
              <strong>Joining an existing chain?</strong> Do <em>not</em> run a fresh{" "}
              <code className="bg-amber-950/40 px-1 rounded">init</code> with your own key and
              network up — your <code className="bg-amber-950/40 px-1 rounded">timestamp</code> and{" "}
              <code className="bg-amber-950/40 px-1 rounded">alloc</code> will differ from the
              founder's, producing a different genesis hash and instant divergence. Copy the
              founder's <code className="bg-amber-950/40 px-1 rounded">genesis.json</code> verbatim
              into your <code className="bg-amber-950/40 px-1 rounded">--home</code> directory
              before starting the node.
            </span>
          </div>
        </CardContent>
      </Card>

      {/* Customizing alloc */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <Coins className="w-4 h-4 text-primary" /> Customizing the pre-mine
          </CardTitle>
          <CardDescription>
            Only relevant when bootstrapping a fresh network — meaningless on an existing chain.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <p className="text-sm text-muted-foreground">
            By default, the validator address receives the full <strong>9,990,000 ZBX
            Foundation pre-mine</strong> (6.66% of max supply, used for development, operations,
            marketing, and team expenses). You can override this with explicit{" "}
            <code className="text-xs bg-muted px-1 rounded">--alloc addr:amount_zbx</code> entries
            (repeatable), or skip the pre-mine entirely with{" "}
            <code className="text-xs bg-muted px-1 rounded">--no-default-premine</code>.
          </p>

          <CodeBlock
            language="bash"
            code={`# Default — founder gets the full 6.66% Foundation pre-mine
zebvix-node init --home /root/.zebvix \\
    --validator-key /root/.zebvix/validator.key

# Custom split — three addresses, no default applied
zebvix-node init --home /root/.zebvix \\
    --validator-key /root/.zebvix/validator.key \\
    --alloc 0xfounder...:5000000 \\
    --alloc 0xfoundation...:3000000 \\
    --alloc 0xteam...:1990000

# No pre-mine at all — admin earns ZBX only via block rewards + swap fees
zebvix-node init --home /root/.zebvix \\
    --validator-key /root/.zebvix/validator.key \\
    --no-default-premine`}
          />

          <div className="grid grid-cols-1 md:grid-cols-3 gap-3 pt-1">
            <div className="rounded-md border border-border/60 bg-muted/30 p-3">
              <div className="text-xs uppercase tracking-wide text-muted-foreground mb-1">Founder pre-mine</div>
              <div className="text-lg font-bold font-mono text-foreground">9,990,000 ZBX</div>
              <div className="text-xs text-muted-foreground mt-1">6.66% of cap · written into genesis.alloc</div>
            </div>
            <div className="rounded-md border border-border/60 bg-muted/30 p-3">
              <div className="text-xs uppercase tracking-wide text-muted-foreground mb-1">Genesis AMM seed</div>
              <div className="text-lg font-bold font-mono text-foreground">20,000,000 ZBX</div>
              <div className="text-xs text-muted-foreground mt-1">13.33% · seeded into the AMM at network bootstrap</div>
            </div>
            <div className="rounded-md border border-border/60 bg-muted/30 p-3">
              <div className="text-xs uppercase tracking-wide text-muted-foreground mb-1">Mineable supply</div>
              <div className="text-lg font-bold font-mono text-foreground">120,010,000 ZBX</div>
              <div className="text-xs text-muted-foreground mt-1">80.01% · 3 ZBX/block, halving every 25M blocks</div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* node.json sidecar */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <Lock className="w-4 h-4 text-primary" /> Sidecar: <code className="text-sm">node.json</code>
          </CardTitle>
          <CardDescription>
            Per-node configuration written alongside genesis. Safe to differ across operators.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <p className="text-sm text-muted-foreground">
            <code className="text-xs bg-muted px-1 rounded">init</code> also writes a tiny{" "}
            <code className="text-xs bg-muted px-1 rounded">node.json</code> next to the genesis
            file. It only stores the absolute path of this node's validator key — that's how{" "}
            <code className="text-xs bg-muted px-1 rounded">start</code> finds the key without you
            re-passing <code className="text-xs bg-muted px-1 rounded">--validator-key</code> on
            every launch.
          </p>
          <CodeBlock
            language="json"
            code={`{
  "validator_key_file": "/root/.zebvix/validator.key"
}`}
          />
          <p className="text-xs text-muted-foreground">
            Unlike <code className="bg-muted px-1 rounded">genesis.json</code>, this file is
            node-specific and <strong>must not</strong> be copied between operators. If you move
            the key file, update this path or just re-run{" "}
            <code className="bg-muted px-1 rounded">init</code> (it overwrites{" "}
            <code className="bg-muted px-1 rounded">node.json</code> + {" "}
            <code className="bg-muted px-1 rounded">genesis.json</code> but leaves{" "}
            <code className="bg-muted px-1 rounded">data/</code> untouched).
          </p>
        </CardContent>
      </Card>

      {/* Inspect / verify */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <GitBranch className="w-4 h-4 text-primary" /> Inspect &amp; verify
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <p className="text-sm text-muted-foreground">
            On any running node, dump the loaded genesis fields directly via RPC and confirm they
            match what the founder published. A mismatch on any of <em>chain_id</em>,{" "}
            <em>max_supply_wei</em>, <em>block_time_secs</em>, or the founder validator address
            means you are on the wrong network or have a stale source build.
          </p>
          <CodeBlock
            language="bash"
            code={`# 1. Read genesis from disk
cat /root/.zebvix/genesis.json | jq .

# 2. Verify chain_id matches what the live RPC reports
curl -s -X POST http://127.0.0.1:8545 -H 'Content-Type: application/json' \\
    --data '{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}' | jq -r .result
# expect: "0x1ec6"   (= 7878)

# 3. Confirm the founder address is present in the active validator set.
#    On a freshly bootstrapped chain this list contains just the founder;
#    on a mature chain it also includes any validators added post-genesis
#    via the two-tier governance flow (StakeOp::CreateValidator + ValidatorAdd).
curl -s -X POST http://127.0.0.1:8545 -H 'Content-Type: application/json' \\
    --data '{"jsonrpc":"2.0","id":1,"method":"zbx_listValidators","params":[]}' | jq .

# 4. Sanity-check supply hasn't exceeded the cap
curl -s -X POST http://127.0.0.1:8545 -H 'Content-Type: application/json' \\
    --data '{"jsonrpc":"2.0","id":1,"method":"zbx_supply","params":[]}' | jq .`}
          />
        </CardContent>
      </Card>

      {/* Footer */}
      <div className="rounded-lg border border-border/60 bg-muted/30 p-4 text-xs text-muted-foreground flex items-start gap-2">
        <ShieldCheck className="w-4 h-4 text-primary flex-shrink-0 mt-0.5" />
        <span>
          <strong className="text-foreground">Source of truth:</strong>{" "}
          <code className="bg-muted px-1 rounded">struct GenesisFile</code> in{" "}
          <code className="bg-muted px-1 rounded">zebvix-chain/src/main.rs</code>,{" "}
          <code className="bg-muted px-1 rounded">FOUNDER_PUBKEY_HEX</code> +{" "}
          <code className="bg-muted px-1 rounded">TOTAL_SUPPLY_WEI</code> +{" "}
          <code className="bg-muted px-1 rounded">BLOCK_TIME_SECS</code> in{" "}
          <code className="bg-muted px-1 rounded">tokenomics.rs</code>. Any change to those
          constants is a chain-breaking event — coordinate via Phase-D forkless governance.
        </span>
      </div>
    </div>
  );
}
