uploads = []
generated = []

[[outputs]]
id = "OoWVMTCdLxL4ByhdeHoCP"
uri = "file://zebvix-chain-patches.tar.gz"
type = "unspecified"
title = "zebvix-chain-patches.tar.gz — Zebvix Chain Final Patches"

[[outputs]]
id = "gZJ4vWcea7Digo2czosZY"
uri = "file://zebvix-full-source.tar.gz"
type = "unspecified"
title = "zebvix-full-source.tar.gz — Complete Zebvix Chain Source Code (78MB)"

[[outputs]]
id = "B9kmaWIdWag9BR2TJC2pO"
uri = "file://zebvix-chain-patches.zip"
type = "unspecified"
title = "Zebvix Chain Patches — zebvix-chain-patches.zip"

[[outputs]]
id = "Tzb11uSYeVGUuPhv6D69g"
uri = "file://zebvix-full-source.zip"
type = "unspecified"
title = "Zebvix Full Chain Source — zebvix-full-source.zip (87.5MB)"

[[outputs]]
id = "dpA0i0VVNrAX3e3mL4IMv"
uri = "file://zebvix-chain-source.tar.gz"
type = "unspecified"
title = "zebvix-chain v0.2-alpha (Phase A: P2P)"
