// Maps the iconName strings stored by the admin panel back to lucide React
// components so we can render dynamic nav items. Covers every icon used in
// the seeded DEFAULT_NAV plus the icons exposed by the admin "Add custom"
// dropdown. Unknown names fall back to the generic Link icon.
import {
  Activity,
  ArrowDownUp,
  ArrowLeftRight,
  ArrowUpDown,
  AtSign,
  BookOpen,
  Calculator,
  CheckSquare,
  Code2,
  Coins,
  Cpu,
  Download,
  Droplets,
  FileCode2,
  FileJson,
  GitBranch,
  Hammer,
  Info,
  KeyRound,
  Layers,
  Link as LinkIcon,
  ListChecks,
  Lock,
  Map,
  Network,
  Package,
  Paintbrush,
  PlayCircle,
  Rocket,
  Search,
  Settings,
  Shield,
  Smartphone,
  Sparkles,
  Star,
  Terminal,
  TerminalSquare,
  TrendingUp,
  UserPlus,
  Users,
  Vote,
  Wallet,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  Activity,
  ArrowDownUp,
  ArrowLeftRight,
  ArrowUpDown,
  AtSign,
  BookOpen,
  Calculator,
  CheckSquare,
  Code2,
  Coins,
  Cpu,
  Download,
  Droplets,
  FileCode2,
  FileJson,
  GitBranch,
  Hammer,
  Info,
  KeyRound,
  Layers,
  Link: LinkIcon,
  ListChecks,
  Lock,
  Map,
  Network,
  Package,
  Paintbrush,
  PlayCircle,
  Rocket,
  Search,
  Settings,
  Shield,
  Smartphone,
  Sparkles,
  Star,
  Terminal,
  TerminalSquare,
  TrendingUp,
  UserPlus,
  Users,
  Vote,
  Wallet,
};

export function iconFor(name: string | null | undefined): LucideIcon {
  if (!name) return LinkIcon;
  return ICON_MAP[name] ?? LinkIcon;
}
